import { devLog, fetchGraphQLSS, fetchPublicSS, generateRandomId } from './utils';
import { authStore } from '../stores/authStore';

export interface SignatureRequest {
  id: string;
  accessToken?: string; // Generated by backend for public access
  refId?: string;
  clientId: string;
  clientName: string;
  clientEmail: string;
  clientPhone?: string;
  requestedBy: string;
  requestedByName: string;
  businessId: string;
  businessName: string;
  storeId?: string;
  storeName?: string;
  createdAt: number;
  expiresAt: number;
  status: 'pending' | 'signed' | 'expired' | 'cancelled' | 'exported';
  signedAt?: number;
  exportedAt?: number;
  signatureUrl?: string;
  documentType?: string;
  documentReference?: string;
  notes?: string;
  metadata?: Record<string, any>;
  // Additional fields from backend
  title?: string;
  signerId?: string;
  signerName?: string;
  signerEmail?: string;
  signerPhone?: string;
}

export interface SignatureCapture {
  requestId: string;
  signatureDataUrl: string;
  signedAt: Date;
  deviceInfo?: {
    userAgent: string;
    platform: string;
    language: string;
  };
}

export interface SignatureFile {
  url?: string;
  blob?: Blob;
  base64?: string;
  storageRef?: string;
  metadata?: {
    size: number;
    timeCreated: string;
    updated: string;
    contentType: string;
    name: string;
  };
  storageMethod: 'storage' | 'base64' | 'blob';
}

// Generate a unique signature request ID
const generateRequestId = (): string => {
  const timestamp = Date.now().toString(36);
  const randomStr = Math.random().toString(36).substring(2, 8);
  return `SIG-${timestamp}-${randomStr}`.toUpperCase();
};

// Create a new signature request
export const createSignatureRequest = async (
  clientData: {
    refId?: string;
    clientId: string;
    clientName: string;
    clientEmail: string;
    clientPhone?: string;
    documentType?: string;
    documentReference?: string;
    notes?: string;
    storeId?: string;
    businessId?: string;
    storeName?: string;
    metadata?: Record<string, any>;
  },
  expirationDays: number = 7
): Promise<SignatureRequest> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser?.uid) {
     // throw new Error('Usuario no autenticado');
    }

    const requestId = generateRequestId();
    const now = Date.now();
    const expiresAt = now + expirationDays * 24 * 60 * 60 * 1000;

    const signatureRequest: SignatureRequest = {
      id: requestId,
      title: clientData.clientId,
      refId: clientData.refId || '',
      signerId: clientData.clientId,
      signerName: clientData.clientName,
      signerEmail: clientData.clientEmail,
      requestedBy: currentUser?.uid,
      requestedByName: currentUser?.displayName || currentUser?.email || 'Unknown',
      businessId: authStore.getBusinessId() || currentUser?.uid,
      businessName: authStore.state.profile?.businessName || 'Default Business',
      createdAt: now,
      expiresAt,
      status: 'pending'
    };

    // Add optional fields only if they have values
    if (clientData.signerPhone) signatureRequest.signerPhone = clientData.clientPhone;
    if (clientData.documentType) signatureRequest.documentType = clientData.documentType;
    if (clientData.documentReference) signatureRequest.documentReference = clientData.documentReference;
    if (clientData.notes) signatureRequest.notes = clientData.notes;
    if (clientData.storeId) signatureRequest.storeId = clientData.storeId;
    if (clientData.storeName) signatureRequest.storeName = clientData.storeName;
    if (clientData.metadata) signatureRequest.metadata = clientData.metadata;

    const body = {
      query: "addSignatureRequest",
      params: {
        businessId: authStore.getBusinessId()
      },
      form: signatureRequest
    };

    devLog('Creating signature request:', body);
    const response = await fetchGraphQLSS(body);
    devLog('Create signature response:', response);

    // Backend returns the created request with accessToken
    const created = response?.data?.signatureRequest || response?.data || response?.signatureRequest || signatureRequest;
    return created;
  } catch (error) {
    console.error('Error creating signature request:', error);
    throw new Error('Error al crear la solicitud de firma');
  }
};

// Get signature request by ID (public access for signing)
export const getSignatureRequest = async (requestId: string, accessToken?: string): Promise<SignatureRequest | null> => {
  try {
    devLog('getSignatureRequest - Fetching request ID:', requestId);

    // Build params - use accessToken for public access or businessId for authenticated access
    const params: Record<string, any> = {
      id: requestId
    };

    // Add businessId if available (authenticated access)
    const businessId = authStore.getBusinessId();
    if (businessId) {
      params.businessId = businessId;
    }

    // Add accessToken for public access (when client clicks signature link)
    if (accessToken) {
      params.accessToken = accessToken;
    }

    const body = {
      query: "getSignatureRequestById",
      params
    };

    devLog('getSignatureRequest - Request body:', body);
    const response = await fetchGraphQLSS(body);
    devLog('getSignatureRequest - Response:', response);

    // Handle nested response structure
    const data = response?.data?.signatureRequest || response?.data || response?.signatureRequest;

    if (!data) {
      devLog('getSignatureRequest - Document not found');
      return null;
    }

    // Check if expired
    if (data.expiresAt < Date.now() && data.status === 'pending') {
      devLog('getSignatureRequest - Request expired, updating status');
      try {
        await updateSignatureRequestStatus(requestId, 'expired');
      } catch (e) {
        // Ignore update error for public access
      }
      data.status = 'expired';
    }

    devLog('getSignatureRequest - Returning data:', data);
    return data;
  } catch (error) {
    console.error('Error getting signature request:', error);
    return null;
  }
};

// Update signature request status
const updateSignatureRequestStatus = async (
  requestId: string,
  status: SignatureRequest['status'],
  additionalData?: Partial<SignatureRequest>
): Promise<void> => {
  const body = {
    query: "updateSignatureRequest",
    params: {
      businessId: authStore.getBusinessId(),
      id: requestId
    },
    form: {
      status,
      ...additionalData
    }
  };

  await fetchGraphQLSS(body);
};

// Save captured signature
export const saveSignature = async (capture: SignatureCapture): Promise<string> => {
  try {
    const request = await getSignatureRequest(capture.requestId);
    if (!request) {
      throw new Error('Solicitud de firma no encontrada');
    }

    if (request.status !== 'pending') {
      throw new Error(`La solicitud está ${request.status}. No se puede firmar.`);
    }

    const signatureUrl = capture.signatureDataUrl;

    // Validate that we're actually saving base64 data
    if (!signatureUrl.startsWith('data:image/')) {
      throw new Error('Invalid signature format: must be base64 data URL');
    }

    const base64Size = Math.round((signatureUrl.length * 3) / 4);
    devLog(`Signature saved as base64 - Size: ${Math.round(base64Size / 1024)}KB`);

    const body = {
      query: "updateSignatureRequest",
      params: {
        businessId: request.businessId,
       
      },
      form: {
        clientId: capture.requestId,
        status: 'signed',
        signedAt: capture.signedAt.getTime(),
        signatureUrl,
        signatureData: signatureUrl,
        deviceInfo: capture.deviceInfo
      }
    };

    devLog(`Updating signature request ${capture.requestId} with signature`);
    await fetchGraphQLSS(body);

    // Also save to client signatures collection
    const clientSignatureBody = {
      query: "addClientSignature",
      params: {
        businessId: request.businessId
      },
      form: {
        id: `${request.clientId}_${capture.requestId}`,
        clientId: request.clientId,
        clientName: request.clientName,
        requestId: capture.requestId,
        signatureUrl,
        signedAt: capture.signedAt.getTime(),
        documentType: request.documentType,
        documentReference: request.documentReference,
        metadata: request.metadata,
        storageMethod: 'base64'
      }
    };

    devLog(`Saving to clientSignatures/${request.clientId}_${capture.requestId}`);
    await fetchGraphQLSS(clientSignatureBody);

    return signatureUrl;
  } catch (error) {
    console.error('Error saving signature:', error);
    throw error;
  }
};

// Get all signature requests for current user's business
export const getBusinessSignatureRequests = async (
  filters?: {
    status?: 'pending' | 'signed' | 'expired' | 'cancelled' | 'exported';
    clientId?: string;
    limit?: number;
  }
): Promise<SignatureRequest[]> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser) {
      throw new Error('Usuario no autenticado');
    }

    const businessId = authStore.getBusinessId() || currentUser.uid;

    const body = {
      query: "getSignatureRequests",
      params: {
        businessId
      }
    };

    const response = await fetchGraphQLSS(body);
    // Handle nested response structure: response.data.data or response.data
    let requests: SignatureRequest[] = response?.data?.data || response?.data || [];

    // Filter requests by user's allowed stores (unless admin)
    if (!authStore.isAdmin()) {
      const allowedStoreIds = authStore.getAllowedStoreIds();
      requests = requests.filter(request => {
        if (!request.storeId) return true;
        return allowedStoreIds.includes(request.storeId);
      });
    }
    devLog({requests})
    // Sort by createdAt descending
    requests.sort((a, b) => b.createdAt - a.createdAt);

    // Apply filters
    if (filters?.status) {
      requests = requests.filter(r => r.status === filters.status);
    }
    if (filters?.clientId) {
      requests = requests.filter(r => r.clientId === filters.clientId);
    }
    if (filters?.limit) {
      requests = requests.slice(0, filters.limit);
    }

    return requests;
  } catch (error) {
    console.error('Error getting business signature requests:', error);
    return [];
  }
};

// Get all signature requests for current user (legacy function)
export const getMySignatureRequests = async (
  filters?: {
    status?: 'pending' | 'signed' | 'expired' | 'cancelled' | 'exported';
    clientId?: string;
    limit?: number;
  }
): Promise<SignatureRequest[]> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser) {
      throw new Error('Usuario no autenticado');
    }

    const body = {
      query: "getSignatureRequestsByUser",
      params: {
        businessId: authStore.getBusinessId(),
        requestedBy: currentUser.uid
      }
    };

    const response = await fetchGraphQLSS(body);
    // Handle nested response structure: response.data.data or response.data
    let requests: SignatureRequest[] = response?.data?.data || response?.data || [];

    requests.sort((a, b) => b.createdAt - a.createdAt);

    // Apply filters
    if (filters?.status) {
      requests = requests.filter(r => r.status === filters.status);
    }
    if (filters?.clientId) {
      requests = requests.filter(r => r.clientId === filters.clientId);
    }
    if (filters?.limit) {
      requests = requests.slice(0, filters.limit);
    }

    return requests;
  } catch (error) {
    console.error('Error getting signature requests:', error);
    return [];
  }
};

// Get client signatures
export const getClientSignatures = async (clientId: string): Promise<any[]> => {
  try {
    const body = {
      query: "getClientSignatures",
      params: {
        businessId: authStore.getBusinessId(),
        clientId
      }
    };

    const response = await fetchGraphQLSS(body);
    // Handle nested response structure: response.data.data or response.data
    const signatures = response?.data?.data || response?.data || [];

    // Sort by signedAt descending
    return signatures.sort((a: any, b: any) => {
      const aTime = a.signedAt || 0;
      const bTime = b.signedAt || 0;
      return bTime - aTime;
    });
  } catch (error) {
    console.error('Error getting client signatures:', error);
    return [];
  }
};

// Cancel a signature request
export const cancelSignatureRequest = async (requestId: string): Promise<void> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser) {
      throw new Error('Usuario no autenticado');
    }

    const request = await getSignatureRequest(requestId);
    if (!request) {
      throw new Error('Solicitud no encontrada');
    }

    if (request.requestedBy !== currentUser.uid && !authStore.isAdmin()) {
      throw new Error('No autorizado para cancelar esta solicitud');
    }

    if (request.status !== 'pending') {
      throw new Error('Solo se pueden cancelar solicitudes pendientes');
    }

    await updateSignatureRequestStatus(requestId, 'cancelled');
  } catch (error) {
    console.error('Error cancelling signature request:', error);
    throw error;
  }
};

// Delete signature request
export const deleteSignatureRequest = async (requestId: string): Promise<void> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser) {
      throw new Error('Usuario no autenticado');
    }

    const request = await getSignatureRequest(requestId);
    if (!request) {
      throw new Error('Solicitud no encontrada');
    }

    // Only admin or the creator can delete
    if (!authStore.isAdmin() && request.requestedBy !== currentUser.uid) {
      throw new Error('No autorizado para eliminar esta solicitud');
    }

    const body = {
      query: "deleteSignatureRequest",
      params: {
        businessId: authStore.getBusinessId(),
        id: requestId
      }
    };

    await fetchGraphQLSS(body);

    // If the request was signed, also delete from clientSignatures
    if (request.status === 'signed' && request.clientId) {
      try {
        const deleteClientSigBody = {
          query: "deleteClientSignature",
          params: {
            businessId: authStore.getBusinessId(),
            id: `${request.clientId}_${requestId}`
          }
        };
        await fetchGraphQLSS(deleteClientSigBody);
      } catch (error) {
        console.warn('Could not delete from clientSignatures:', error);
      }
    }

    devLog(`Successfully deleted signature request: ${requestId}`);
  } catch (error) {
    console.error('Error deleting signature request:', error);
    throw error;
  }
};

// Generate shareable link using accessToken (for public access without login)
export const generateSignatureLink = (accessToken: string, id: string): string => {
  const baseUrl = window.location.origin;
  return `${baseUrl}/#/sign/${id}/${accessToken}`;
};

// Generate QR code data URL for the signature link
export const generateSignatureQR = async (accessToken: string, id: string): Promise<string> => {
  const link = generateSignatureLink(accessToken, id);
  return `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(link)}`;
};

// Get signature request by accessToken (PUBLIC - no login required)
export const getSignatureRequestByToken = async (accessToken: string, id: string ): Promise<SignatureRequest | null> => {
  try {
    devLog('getSignatureRequestByToken - Fetching by token:', accessToken);

    const body = {
      query: "getSignatureRequestByToken",
      params: {
        accessToken,
        id
      }
    };

    const response = await fetchPublicSS(body);
    devLog('getSignatureRequestByToken - Response:', response);

    // Handle nested response structure
    const data = response?.data?.signatureRequest || response?.data || response?.signatureRequest;

    if (!data) {
      devLog('getSignatureRequestByToken - Document not found');
      return null;
    }

    // Check if expired
    if (data.expiresAt < Date.now() && data.status === 'pending') {
      data.status = 'expired';
    }

    return data;
  } catch (error) {
    console.error('Error getting signature request by token:', error);
    return null;
  }
};

// Save signature (PUBLIC - uses accessToken for auth)
export const saveSignaturePublic = async (
  id: string,
  accessToken: string,
  signatureDataUrl: string,
  deviceInfo?: { userAgent: string; platform: string; language: string }
): Promise<string> => {
  try {
    const request = await getSignatureRequestByToken(accessToken, id);
    if (!request) {
      throw new Error('Solicitud de firma no encontrada');
    }

    if (request.status !== 'pending') {
     // throw new Error(`La solicitud está ${request.status}. No se puede firmar.`);
    }

    // Validate signature format
    if (!signatureDataUrl.startsWith('data:image/')) {
      throw new Error('Invalid signature format: must be base64 data URL');
    }

    const signedAt = Date.now();

    const body = {
      query: "submitSignatureByToken",
      params: {
        id,
        accessToken
      },
      form: {
        status: 'signed',
        signedAt,
        signatureUrl: signatureDataUrl,
        signatureData: signatureDataUrl,
        deviceInfo
      }
    };

    devLog('Saving signature via public endpoint');
    await fetchPublicSS(body);

    return signatureDataUrl;
  } catch (error) {
    console.error('Error saving signature:', error);
    throw error;
  }
};

// Get signature file with metadata
export const getSignatureFile = async (request: SignatureRequest): Promise<SignatureFile | null> => {
  if (!request.signatureUrl) {
    return null;
  }

  // If it's a base64 data URL, return it as-is
  if (request.signatureUrl.startsWith('data:')) {
    return {
      url: request.signatureUrl,
      base64: request.signatureUrl,
      storageMethod: 'base64'
    };
  }

  // If it's a URL, return it
  return {
    url: request.signatureUrl,
    storageMethod: 'storage'
  };
};

// Get multiple signature files with metadata
export const getSignatureFiles = async (requests: SignatureRequest[]): Promise<(SignatureFile | null)[]> => {
  const promises = requests.map(request => getSignatureFile(request));
  return Promise.all(promises);
};

// Export signed requests to main database and mark as exported
export const exportSignedRequests = async (requestIds: string[]): Promise<{
  success: string[];
  errors: { id: string; error: string }[];
}> => {
  const results = {
    success: [] as string[],
    errors: [] as { id: string; error: string }[]
  };

  for (const requestId of requestIds) {
    try {
      const request = await getSignatureRequest(requestId);
      if (!request) {
        results.errors.push({ id: requestId, error: 'Request not found' });
        continue;
      }

      if (request.status !== 'signed') {
        results.errors.push({ id: requestId, error: 'Request is not signed' });
        continue;
      }

      const now = Date.now();

      // Create exported record
      const exportBody = {
        query: "addExportedSignature",
        params: {
          businessId: authStore.getBusinessId()
        },
        form: {
          ...request,
          exportedAt: now,
          originalRequestId: requestId
        }
      };

      await fetchGraphQLSS(exportBody);

      // Mark original request as exported
      await updateSignatureRequestStatus(requestId, 'exported', { exportedAt: now });

      results.success.push(requestId);
    } catch (error: any) {
      results.errors.push({
        id: requestId,
        error: error.message || 'Unknown error during export'
      });
    }
  }

  return results;
};

// Clean up exported requests
export const cleanupExportedRequests = async (requestIds: string[]): Promise<{
  success: string[];
  errors: { id: string; error: string }[];
}> => {
  const results = {
    success: [] as string[],
    errors: [] as { id: string; error: string }[]
  };

  for (const requestId of requestIds) {
    try {
      const request = await getSignatureRequest(requestId);
      if (!request) {
        results.errors.push({ id: requestId, error: 'Request not found' });
        continue;
      }

      if (request.status !== 'exported') {
        results.errors.push({ id: requestId, error: 'Request is not exported yet' });
        continue;
      }

      await deleteSignatureRequest(requestId);
      results.success.push(requestId);
    } catch (error: any) {
      results.errors.push({
        id: requestId,
        error: error.message || 'Unknown error during cleanup'
      });
    }
  }

  return results;
};

// Get exported signatures from main database
export const getExportedSignatures = async (): Promise<SignatureRequest[]> => {
  try {
    const currentUser = authStore.state.user;
    if (!currentUser) {
      throw new Error('Usuario no autenticado');
    }

    const businessId = authStore.getBusinessId() || currentUser.uid;

    const body = {
      query: "getExportedSignatures",
      params: {
        businessId
      }
    };

    const response = await fetchGraphQLSS(body);
    // Handle nested response structure: response.data.data or response.data
    let requests: SignatureRequest[] = response?.data?.data || response?.data || [];

    requests.sort((a, b) => (b.exportedAt || 0) - (a.exportedAt || 0));

    return requests;
  } catch (error) {
    console.error('Error getting exported signatures:', error);
    return [];
  }
};

// Helper to format file size
export const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};
