/**
 * Supervision Module Types
 *
 * Type definitions for the supervision system that manages adapters,
 * field mappings, and account mappings with AI-assisted suggestions
 * and user oversight capabilities.
 */

// ============================================================================
// Enums
// ============================================================================

/**
 * Represents the lock status of an entity (adapter, mapping, etc.)
 */
export enum LockStatus {
  /** Entity can be modified by AI or users */
  UNLOCKED = 'UNLOCKED',
  /** Entity is locked by AI processing */
  AI_LOCKED = 'AI_LOCKED',
  /** Entity is locked by a user */
  USER_LOCKED = 'USER_LOCKED',
  /** Entity has pending changes awaiting review */
  PENDING_REVIEW = 'PENDING_REVIEW',
}

/**
 * Indicates the origin/source of a mapping
 */
export enum MappingSource {
  /** Mapping was generated by AI */
  AI_GENERATED = 'AI_GENERATED',
  /** Mapping was created by a user */
  USER_CREATED = 'USER_CREATED',
  /** Mapping was modified by a user after initial creation */
  USER_MODIFIED = 'USER_MODIFIED',
  /** Mapping is a system default */
  SYSTEM_DEFAULT = 'SYSTEM_DEFAULT',
}

// ============================================================================
// Lock Information
// ============================================================================

/**
 * Information about the lock state of an entity
 */
export interface LockInfo {
  /** Current lock status */
  status: LockStatus;
  /** ID of the user or system that holds the lock */
  lockedBy: string | null;
  /** Timestamp when the lock was acquired */
  lockedAt: Date | null;
  /** Reason for the lock */
  reason: string | null;
}

// ============================================================================
// Adapter Types
// ============================================================================

/**
 * Rule used to detect which adapter should process a given input
 */
export interface AdapterDetectionRule {
  /** Unique identifier for the rule */
  id: string;
  /** Name of the detection rule */
  name: string;
  /** Field path to check in the source data */
  field: string;
  /** Operator for comparison */
  operator: 'equals' | 'contains' | 'startsWith' | 'endsWith' | 'matches' | 'exists';
  /** Value to compare against */
  value: string | RegExp | null;
  /** Priority order (lower = higher priority) */
  priority: number;
  /** Whether this rule is currently active */
  isActive: boolean;
}

/**
 * Version history entry for an adapter
 */
export interface AdapterVersion {
  /** Version number */
  version: number;
  /** Timestamp of this version */
  timestamp: Date;
  /** ID of user who made the change */
  changedBy: string;
  /** Description of changes */
  changeDescription: string;
  /** Snapshot of adapter state at this version */
  snapshot: Partial<SupervisedAdapter>;
}

/**
 * A supervised adapter that processes data with AI assistance and user oversight
 */
export interface SupervisedAdapter {
  /** Unique identifier */
  id: string;
  /** Associated business ID */
  businessId?: string;
  /** Internal name of the adapter */
  name: string;
  /** Human-readable display name */
  displayName?: string;
  /** Description of the adapter's purpose */
  description?: string;
  /** Source system this adapter handles - API format */
  sourceSystem?: string;
  /** Source type - UI-friendly alias */
  sourceType?: string;
  /** Rules for detecting when this adapter should be used */
  detectionRules?: AdapterDetectionRule[];
  /** Field mappings for this adapter */
  fieldMappings?: SupervisedFieldMapping[];
  /** Array mappings */
  arrayMappings?: any[];
  /** Default values */
  defaultValues?: any[];
  /** Global lock status for the entire adapter - API format */
  globalLock?: LockInfo;
  /** Quick boolean check for lock status - UI-friendly */
  isLocked?: boolean;
  /** Lock info - UI-friendly format */
  lockInfo?: { status: string; lockedBy?: string; lockedAt?: string; reason?: string };
  /** AI confidence score (0-1) */
  confidence: number;
  /** Total number of records processed */
  processedCount?: number;
  /** Number of successful processing operations */
  successCount?: number;
  /** Number of failed processing operations */
  failureCount?: number;
  /** Success rate percentage (0-100) */
  successRate?: number;
  /** Current version number */
  version?: number;
  /** Previous version history */
  previousVersions?: AdapterVersion[];
  /** Pending AI suggestions awaiting review */
  pendingSuggestions?: AISuggestion[];
  /** Timestamp information - structured format */
  timestamps?: {
    createdAt: Date;
    updatedAt: Date;
    lastProcessedAt: Date | null;
  };
  /** Flat timestamp fields - UI-friendly */
  createdAt?: string;
  updatedAt?: string;
  lastProcessedAt?: string;
}

// ============================================================================
// Field Mapping Types
// ============================================================================

/**
 * Transform types that can be applied to field values
 */
export type FieldTransform =
  | 'none'
  | 'uppercase'
  | 'lowercase'
  | 'trim'
  | 'toNumber'
  | 'toString'
  | 'toDate'
  | 'toBoolean'
  | 'parseJSON'
  | 'stringifyJSON'
  | 'split'
  | 'join'
  | 'replace'
  | 'extract'
  | 'custom';

/**
 * Test case for validating a field mapping
 */
export interface FieldMappingTestCase {
  /** Unique identifier for the test case */
  id: string;
  /** Description of what this test validates */
  description: string;
  /** Input value for the test */
  input: unknown;
  /** Expected output value */
  expectedOutput: unknown;
  /** Whether the test is currently passing */
  isPassing: boolean;
  /** Last time this test was run */
  lastRunAt: Date | null;
  /** Error message if test failed */
  errorMessage: string | null;
}

/**
 * Version history entry for a field mapping
 */
export interface FieldMappingVersion {
  /** Version number */
  version: number;
  /** Timestamp of this version */
  timestamp: Date;
  /** ID of user who made the change */
  changedBy: string;
  /** Description of changes */
  changeDescription: string;
  /** Snapshot of mapping state at this version */
  snapshot: Partial<SupervisedFieldMapping>;
}

/**
 * A supervised field mapping with AI assistance and user oversight
 */
export interface SupervisedFieldMapping {
  /** Unique identifier */
  id: string;
  /** Adapter this mapping belongs to */
  adapterId?: string;
  /** Source field path (dot notation for nested fields) - API format */
  sourcePath?: string;
  /** Target field path (dot notation for nested fields) - API format */
  targetPath?: string;
  /** Source field - UI-friendly alias */
  sourceField?: string;
  /** Target field - UI-friendly alias */
  targetField?: string;
  /** Transform to apply to the value - can be string or object */
  transform: FieldTransform | { type: string; params?: Record<string, any> };
  /** Custom transform code (when transform is 'custom') */
  customTransformCode?: string | null;
  /** Lock status for this mapping - API format */
  lock?: LockInfo;
  /** Quick boolean check for lock status - UI-friendly */
  isLocked?: boolean;
  /** Lock info - UI-friendly format */
  lockInfo?: { status: string; lockedBy?: string; lockedAt?: string; reason?: string };
  /** Source/origin of this mapping */
  source: MappingSource | string;
  /** ID of user who created this mapping */
  createdBy?: string;
  /** AI confidence score for this mapping (0-1) */
  confidence: number;
  /** Number of times this mapping has been used */
  usageCount?: number;
  /** Number of successful uses */
  successCount?: number;
  /** Number of failed uses */
  failureCount?: number;
  /** Success rate percentage (0-100) */
  successRate?: number;
  /** Automatically lock after this many successful uses */
  autoLockAfterSuccesses?: number | null;
  /** Current version number */
  version?: number;
  /** Previous version history */
  previousVersions?: FieldMappingVersion[];
  /** Test cases for validating this mapping */
  testCases?: FieldMappingTestCase[];
  /** Timestamp information */
  createdAt?: string;
  updatedAt?: string;
}

// ============================================================================
// Account Mapping Types
// ============================================================================

/**
 * Reference to an account in the chart of accounts
 */
export interface AccountReference {
  /** Account ID */
  id: string;
  /** Account code/number */
  code: string;
  /** Account name */
  name: string;
  /** Account type (asset, liability, equity, revenue, expense) */
  type: string;
  /** Parent account ID (for hierarchical structures) */
  parentId: string | null;
}

/**
 * Criteria for matching transactions to account mappings
 */
export interface AccountMappingCriteria {
  /** Field to match against */
  field: string;
  /** Operator for comparison */
  operator: 'equals' | 'contains' | 'startsWith' | 'endsWith' | 'matches' | 'in' | 'range';
  /** Value(s) to compare against */
  value: string | string[] | number | [number, number];
  /** Whether matching is case-sensitive */
  caseSensitive: boolean;
}

/**
 * A supervised account mapping with AI assistance and user oversight
 */
export interface SupervisedAccountMapping {
  /** Unique identifier */
  id: string;
  /** Associated business ID */
  businessId?: string;
  /** Name/description of this mapping rule */
  name?: string;
  /** Transaction type/pattern - UI-friendly field */
  transactionType?: string;
  /** Account code - for simple display (debit account code) */
  accountCode?: string;
  /** Account name - for simple display (debit account name) */
  accountName?: string;
  /** Criteria that must match for this mapping to apply - can be single object or array */
  criteria?: AccountMappingCriteria[] | any;
  /** Target debit account */
  debitAccount?: AccountReference;
  /** Target credit account */
  creditAccount?: AccountReference;
  /** COGS debit account (for product sales) */
  cogsDebitAccount?: AccountReference;
  /** COGS credit account (for product sales) */
  cogsCreditAccount?: AccountReference;
  /** Lock status for this mapping - raw API format */
  lock?: LockInfo | any;
  /** Quick boolean check for lock status - UI-friendly */
  isLocked?: boolean;
  /** Lock info - UI-friendly format */
  lockInfo?: { status: string; lockedBy?: string; lockedAt?: string; reason?: string };
  /** Source/origin of this mapping - can be enum or string */
  source: MappingSource | string;
  /** ID of user who created this mapping */
  createdBy?: string;
  /** ID of user who last modified this mapping */
  modifiedBy?: string;
  /** AI confidence score for this mapping (0-1) */
  confidence?: number;
  /** Priority order (lower = higher priority) */
  priority?: number;
  /** Whether this mapping is currently active */
  isActive?: boolean;
  /** Number of times this mapping has been used */
  usageCount?: number;
  /** Number of successful uses */
  successCount?: number;
  /** Number of failed uses */
  failureCount?: number;
  /** Success rate (0-1) */
  successRate?: number;
  /** Current version number */
  version?: number;
  /** Previous version history */
  previousVersions?: any[];
  /** Pending AI suggestions for this mapping */
  pendingSuggestions?: AccountSuggestion[];
  /** Timestamp information - structured format */
  timestamps?: {
    createdAt: Date;
    updatedAt: Date;
    lastUsedAt: Date | null;
  };
  /** Flat timestamp fields - UI-friendly */
  createdAt?: string;
  updatedAt?: string;
  lastUsedAt?: string;
}

// ============================================================================
// AI Suggestion Types
// ============================================================================

/**
 * AI-generated suggestion for improving an adapter or mapping
 */
export interface AISuggestion {
  /** Unique identifier */
  id: string;
  /** Type of suggestion */
  type: 'field_mapping' | 'detection_rule' | 'transform' | 'account_mapping' | 'optimization';
  /** Description of the suggested change */
  description: string;
  /** The suggested change data */
  suggestedValue: unknown;
  /** AI confidence in this suggestion (0-1) */
  confidence: number;
  /** Reasoning/explanation for the suggestion */
  reasoning: string;
  /** Current status of the suggestion */
  status: 'pending' | 'accepted' | 'rejected' | 'expired';
  /** ID of user who reviewed this suggestion */
  reviewedBy: string | null;
  /** Timestamp when suggestion was reviewed */
  reviewedAt: Date | null;
  /** Feedback provided during review */
  reviewFeedback: string | null;
  /** Timestamp when suggestion was created */
  createdAt: Date;
  /** Timestamp when suggestion expires */
  expiresAt: Date | null;
}

/**
 * AI-generated suggestion specifically for account mappings
 */
export interface AccountSuggestion {
  /** Unique identifier */
  id: string;
  /** Suggested debit account */
  suggestedDebitAccount: AccountReference;
  /** Suggested credit account */
  suggestedCreditAccount: AccountReference;
  /** AI confidence in this suggestion (0-1) */
  confidence: number;
  /** Reasoning/explanation for the suggestion */
  reasoning: string;
  /** Sample transactions that match this suggestion */
  sampleTransactions: string[];
  /** Current status of the suggestion */
  status: 'pending' | 'accepted' | 'rejected' | 'expired';
  /** ID of user who reviewed this suggestion */
  reviewedBy: string | null;
  /** Timestamp when suggestion was reviewed */
  reviewedAt: Date | null;
  /** Timestamp when suggestion was created */
  createdAt: Date;
}

// ============================================================================
// Dashboard Types
// ============================================================================

/**
 * Dashboard data for supervision overview
 */
export interface SupervisionDashboardData {
  /** Total number of adapters */
  totalAdapters: number;
  /** Number of active adapters */
  activeAdapters: number;
  /** Total number of field mappings */
  totalFieldMappings: number;
  /** Number of locked field mappings */
  lockedFieldMappings: number;
  /** Total number of account mappings */
  totalAccountMappings: number;
  /** Number of locked account mappings */
  lockedAccountMappings: number;
  /** Total pending suggestions across all entities */
  pendingSuggestions: number;
  /** Suggestions by type */
  suggestionsByType: {
    fieldMapping: number;
    detectionRule: number;
    transform: number;
    accountMapping: number;
    optimization: number;
  };
  /** Overall success rate percentage (0-100) */
  overallSuccessRate: number;
  /** Total records processed */
  totalProcessed: number;
  /** Processing statistics by time period */
  processingStats: {
    today: number;
    thisWeek: number;
    thisMonth: number;
  };
  /** Recent activity log */
  recentActivity: {
    id: string;
    type: 'adapter_created' | 'adapter_updated' | 'mapping_created' | 'mapping_updated' | 'suggestion_accepted' | 'suggestion_rejected';
    entityId: string;
    entityName: string;
    userId: string;
    timestamp: Date;
    description: string;
  }[];
  /** Adapters requiring attention (high failure rate or pending suggestions) */
  adaptersRequiringAttention: {
    id: string;
    name: string;
    reason: 'high_failure_rate' | 'pending_suggestions' | 'low_confidence' | 'unlocked';
    value: number;
  }[];
  /** Timestamp when dashboard data was last updated */
  lastUpdated: Date;
}
