/**
 * AutoRecommendations - AI-Powered Tax Strategy Recommendations Panel
 *
 * Displays actionable recommendations generated by the strategy recommendation
 * engine. Cards are sorted by priority and can be filtered by category,
 * dismissed, or applied to the strategy checklist.
 */

import { Component, createSignal, createMemo, For, Show } from 'solid-js';
import type { TaxPortal, DrakeTaxDocument } from '../../../types/drakeTypes';
import type { TaxStrategyData } from '../../../types/taxStrategyTypes';
import {
  generateRecommendations,
  RECOMMENDATION_CATEGORY_LABELS,
  type Recommendation,
  type RecommendationCategory,
} from '../../../services/strategyRecommendationService';

interface AutoRecommendationsProps {
  client: TaxPortal;
  documents: DrakeTaxDocument[];
  strategyData: TaxStrategyData;
  onApplyRecommendation: (recommendation: Recommendation) => void;
}

// ---------------------------------------------------------------------------
// Priority badge colors
// ---------------------------------------------------------------------------

const PRIORITY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  high:   { bg: '#fef2f2', text: '#dc2626', border: '#fecaca' },
  medium: { bg: '#fffbeb', text: '#d97706', border: '#fde68a' },
  low:    { bg: '#eff6ff', text: '#2563eb', border: '#bfdbfe' },
};

// ---------------------------------------------------------------------------
// Category tag colors
// ---------------------------------------------------------------------------

const CATEGORY_COLORS: Record<RecommendationCategory, string> = {
  missed_deductions:  '#8b5cf6',
  credit_opportunities: '#22c55e',
  filing_status:      '#f59e0b',
  retirement:         '#06b6d4',
  estimated_tax:      '#ef4444',
  health_insurance:   '#ec4899',
  business_deductions: '#3b82f6',
  document_gaps:      '#6b7280',
};

const ALL_CATEGORIES: RecommendationCategory[] = [
  'missed_deductions',
  'credit_opportunities',
  'filing_status',
  'retirement',
  'estimated_tax',
  'health_insurance',
  'business_deductions',
  'document_gaps',
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

const AutoRecommendations: Component<AutoRecommendationsProps> = (props) => {
  const [dismissed, setDismissed] = createSignal<Set<string>>(new Set());
  const [activeFilter, setActiveFilter] = createSignal<RecommendationCategory | 'all'>('all');
  const [isGenerating, setIsGenerating] = createSignal(false);
  const [recommendations, setRecommendations] = createSignal<Recommendation[]>([]);

  // Generate recommendations on demand
  const handleGenerate = () => {
    setIsGenerating(true);
    setDismissed(new Set<string>());

    // Small timeout to show the generating state visually
    setTimeout(() => {
      const recs = generateRecommendations(props.client, props.documents, props.strategyData);
      setRecommendations(recs);
      setIsGenerating(false);
    }, 300);
  };

  // Filtered and visible recommendations
  const visibleRecommendations = createMemo(() => {
    const filter = activeFilter();
    const dismissedSet = dismissed();
    return recommendations().filter((r) => {
      if (dismissedSet.has(r.id)) return false;
      if (filter !== 'all' && r.category !== filter) return false;
      return true;
    });
  });

  // Count per category for filter badges
  const categoryCounts = createMemo(() => {
    const counts: Partial<Record<RecommendationCategory, number>> = {};
    const dismissedSet = dismissed();
    for (const r of recommendations()) {
      if (dismissedSet.has(r.id)) continue;
      counts[r.category] = (counts[r.category] || 0) + 1;
    }
    return counts;
  });

  const handleDismiss = (id: string) => {
    setDismissed((prev) => {
      const next = new Set(prev);
      next.add(id);
      return next;
    });
  };

  // -----------------------------------------------------------------------
  // Styles
  // -----------------------------------------------------------------------

  const containerStyle = {
    display: 'flex',
    'flex-direction': 'column' as const,
    gap: '1rem',
  };

  const headerRowStyle = {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
    'flex-wrap': 'wrap' as const,
    gap: '0.75rem',
  };

  const titleStyle = {
    display: 'flex',
    'align-items': 'center',
    gap: '0.5rem',
    'font-weight': '700' as const,
    'font-size': '1rem',
    color: 'var(--text-primary)',
  };

  const generateBtnStyle = () => ({
    padding: '0.5rem 1.25rem',
    background: isGenerating() ? '#94a3b8' : '#8b5cf6',
    color: 'white',
    border: 'none',
    'border-radius': 'var(--border-radius-md, 8px)',
    cursor: isGenerating() ? 'not-allowed' : 'pointer',
    'font-weight': '600',
    'font-size': '0.8125rem',
    transition: 'all 0.2s',
    opacity: isGenerating() ? '0.7' : '1',
  });

  const filtersRowStyle = {
    display: 'flex',
    gap: '0.375rem',
    'flex-wrap': 'wrap' as const,
  };

  const getFilterBtnStyle = (isActive: boolean) => ({
    padding: '0.25rem 0.75rem',
    background: isActive ? '#06b6d4' : 'var(--surface-alt, #f3f4f6)',
    color: isActive ? 'white' : 'var(--text-secondary)',
    border: '1px solid ' + (isActive ? '#06b6d4' : 'var(--border-color, #e5e7eb)'),
    'border-radius': '9999px',
    cursor: 'pointer',
    'font-size': '0.75rem',
    'font-weight': '500',
    transition: 'all 0.15s',
  });

  const cardStyle = (priority: string) => ({
    background: 'var(--surface, white)',
    border: '1px solid var(--border-color, #e5e7eb)',
    'border-left': `4px solid ${PRIORITY_COLORS[priority]?.text || '#6b7280'}`,
    'border-radius': 'var(--border-radius-md, 8px)',
    padding: '1rem',
    transition: 'box-shadow 0.2s',
  });

  const cardHeaderStyle = {
    display: 'flex',
    'align-items': 'flex-start',
    'justify-content': 'space-between',
    gap: '0.75rem',
    'margin-bottom': '0.5rem',
  };

  const priorityBadgeStyle = (priority: string) => {
    const c = PRIORITY_COLORS[priority] || PRIORITY_COLORS.low;
    return {
      display: 'inline-block',
      padding: '0.125rem 0.5rem',
      background: c.bg,
      color: c.text,
      border: `1px solid ${c.border}`,
      'border-radius': '9999px',
      'font-size': '0.6875rem',
      'font-weight': '600',
      'text-transform': 'uppercase' as const,
      'letter-spacing': '0.025em',
      'white-space': 'nowrap' as const,
    };
  };

  const categoryTagStyle = (category: RecommendationCategory) => ({
    display: 'inline-block',
    padding: '0.125rem 0.5rem',
    background: CATEGORY_COLORS[category] + '15',
    color: CATEGORY_COLORS[category],
    'border-radius': '4px',
    'font-size': '0.6875rem',
    'font-weight': '500',
    'white-space': 'nowrap' as const,
  });

  const cardTitleStyle = {
    'font-weight': '600',
    'font-size': '0.9375rem',
    color: 'var(--text-primary)',
    'margin-bottom': '0.25rem',
  };

  const cardDescStyle = {
    'font-size': '0.8125rem',
    color: 'var(--text-secondary)',
    'line-height': '1.5',
  };

  const cardFooterStyle = {
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
    'margin-top': '0.75rem',
    'flex-wrap': 'wrap' as const,
    gap: '0.5rem',
  };

  const savingsStyle = {
    'font-size': '0.875rem',
    'font-weight': '700',
    color: '#16a34a',
  };

  const actionBtnStyle = {
    padding: '0.375rem 0.875rem',
    background: '#06b6d4',
    color: 'white',
    border: 'none',
    'border-radius': 'var(--border-radius-md, 6px)',
    cursor: 'pointer',
    'font-size': '0.75rem',
    'font-weight': '600',
    transition: 'background 0.15s',
  };

  const dismissBtnStyle = {
    padding: '0.375rem 0.75rem',
    background: 'transparent',
    color: 'var(--text-muted, #9ca3af)',
    border: '1px solid var(--border-color, #e5e7eb)',
    'border-radius': 'var(--border-radius-md, 6px)',
    cursor: 'pointer',
    'font-size': '0.75rem',
    transition: 'all 0.15s',
  };

  const emptyStateStyle = {
    display: 'flex',
    'flex-direction': 'column' as const,
    'align-items': 'center',
    'justify-content': 'center',
    padding: '2rem',
    color: 'var(--text-muted, #9ca3af)',
    'text-align': 'center' as const,
    gap: '0.5rem',
  };

  const actionDetailStyle = {
    'margin-top': '0.5rem',
    padding: '0.5rem 0.75rem',
    background: 'var(--surface-alt, #f9fafb)',
    'border-radius': '6px',
    'font-size': '0.8125rem',
    color: 'var(--text-secondary)',
    'border-left': '3px solid #06b6d4',
  };

  const countBadgeStyle = {
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    'min-width': '1.25rem',
    height: '1.25rem',
    'border-radius': '9999px',
    background: '#06b6d4',
    color: 'white',
    'font-size': '0.6875rem',
    'font-weight': '700',
    'margin-left': '0.375rem',
  };

  // -----------------------------------------------------------------------
  // Render
  // -----------------------------------------------------------------------

  return (
    <div style={containerStyle}>
      {/* Header */}
      <div style={headerRowStyle}>
        <div style={titleStyle}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#8b5cf6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
          </svg>
          <span>AI Recommendations</span>
          <Show when={recommendations().length > 0}>
            <span style={countBadgeStyle}>{visibleRecommendations().length}</span>
          </Show>
        </div>
        <button
          style={generateBtnStyle()}
          onClick={handleGenerate}
          disabled={isGenerating()}
        >
          {isGenerating() ? 'Analyzing...' : recommendations().length > 0 ? 'Re-analyze' : 'Generate Recommendations'}
        </button>
      </div>

      {/* Category Filters */}
      <Show when={recommendations().length > 0}>
        <div style={filtersRowStyle}>
          <button
            style={getFilterBtnStyle(activeFilter() === 'all')}
            onClick={() => setActiveFilter('all')}
          >
            All
          </button>
          <For each={ALL_CATEGORIES}>
            {(cat) => {
              const count = () => categoryCounts()[cat] || 0;
              return (
                <Show when={count() > 0}>
                  <button
                    style={getFilterBtnStyle(activeFilter() === cat)}
                    onClick={() => setActiveFilter(cat)}
                  >
                    {RECOMMENDATION_CATEGORY_LABELS[cat]} ({count()})
                  </button>
                </Show>
              );
            }}
          </For>
        </div>
      </Show>

      {/* Recommendation Cards */}
      <Show
        when={!isGenerating()}
        fallback={
          <div style={emptyStateStyle}>
            <div style={{ 'font-size': '1.5rem' }}>...</div>
            <div style={{ 'font-size': '0.875rem' }}>Analyzing tax profile and documents...</div>
          </div>
        }
      >
        <Show
          when={recommendations().length > 0}
          fallback={
            <div style={emptyStateStyle}>
              <div style={{ 'font-size': '0.9375rem', color: 'var(--text-secondary)' }}>
                Click "Generate Recommendations" to analyze the client's tax profile for optimization opportunities.
              </div>
            </div>
          }
        >
          <Show
            when={visibleRecommendations().length > 0}
            fallback={
              <div style={emptyStateStyle}>
                <div style={{ 'font-size': '0.9375rem', 'font-weight': '600', color: 'var(--text-secondary)' }}>
                  No additional recommendations found
                </div>
                <div style={{ 'font-size': '0.8125rem' }}>
                  All recommendations have been dismissed or filtered out. Try a different filter or re-analyze.
                </div>
              </div>
            }
          >
            <div style={{ display: 'flex', 'flex-direction': 'column', gap: '0.75rem' }}>
              <For each={visibleRecommendations()}>
                {(rec) => (
                  <div style={cardStyle(rec.priority)}>
                    {/* Card header: badges */}
                    <div style={cardHeaderStyle}>
                      <div style={{ display: 'flex', 'align-items': 'center', gap: '0.5rem', 'flex-wrap': 'wrap' }}>
                        <span style={priorityBadgeStyle(rec.priority)}>{rec.priority}</span>
                        <span style={categoryTagStyle(rec.category)}>
                          {RECOMMENDATION_CATEGORY_LABELS[rec.category]}
                        </span>
                      </div>
                    </div>

                    {/* Title */}
                    <div style={cardTitleStyle}>{rec.title}</div>

                    {/* Description */}
                    <div style={cardDescStyle}>{rec.description}</div>

                    {/* Action detail */}
                    <Show when={rec.action}>
                      <div style={actionDetailStyle}>
                        <strong>Action:</strong> {rec.action}
                      </div>
                    </Show>

                    {/* Footer: savings + buttons */}
                    <div style={cardFooterStyle}>
                      <div>
                        <Show when={rec.estimatedSavings}>
                          <span style={savingsStyle}>
                            Est. savings: ${rec.estimatedSavings!.toLocaleString()}
                          </span>
                        </Show>
                      </div>
                      <div style={{ display: 'flex', gap: '0.5rem' }}>
                        <Show when={rec.actionable}>
                          <button
                            style={actionBtnStyle}
                            onClick={() => props.onApplyRecommendation(rec)}
                          >
                            Apply
                          </button>
                        </Show>
                        <button
                          style={dismissBtnStyle}
                          onClick={() => handleDismiss(rec.id)}
                        >
                          Dismiss
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </For>
            </div>
          </Show>
        </Show>
      </Show>
    </div>
  );
};

export default AutoRecommendations;
